### ISSUE TITLE
Custom fields are acting weird on chromium-browsers

### ISSUE THREAD

**Issue by Wiggen94** [gibus/RT-Extension-ConditionalCustomFields#13] opened 2023-10-09 12:16 UTC
Hello

On chromium browsers conditional custom fields are not acting as expected. It works fine in Firefox.
When choosing a custom field that has some "underlying" custom fields I sometimes have to choose another value first and then the actual value that has a children custom field to get it to show at all. This applies to both editing a ticket and viewing a ticket.

I can see an error in the console whenever I choose a value that is having children custom fields, if we can call them that.
This error shows whether or not if the children custom field actually shows when choosing the parent field value. It usually shows after going back and forth between values in the parent custom field.

`squished-1febf77661b15f79d8ad92046ccfc105.js:227 Uncaught TypeError: Cannot set properties of undefined (setting '_menu')
    at HTMLDivElement.<anonymous> (squished-1febf77661b15f79d8ad92046ccfc105.js:227:41520)
    at HTMLDivElement.dispatch (squished-1febf77661b15f79d8ad92046ccfc105.js:2:43064)
    at v.handle (squished-1febf77661b15f79d8ad92046ccfc105.js:2:41048)
    at Object.trigger (squished-1febf77661b15f79d8ad92046ccfc105.js:2:71515)
    at HTMLSelectElement.<anonymous> (squished-1febf77661b15f79d8ad92046ccfc105.js:2:72110)
    at Function.each (squished-1febf77661b15f79d8ad92046ccfc105.js:2:3003)
    at S.fn.init.each (squished-1febf77661b15f79d8ad92046ccfc105.js:2:1481)
    at S.fn.init.trigger (squished-1febf77661b15f79d8ad92046ccfc105.js:2:72086)
    at HTMLSelectElement.<anonymous> (Display.html?id=301479:5450:35)
    at HTMLSelectElement.dispatch (squished-1febf77661b15f79d8ad92046ccfc105.js:2:43064)`

This error might also be unrelated to this extension, but the weird behaviour of the custom fields is definitely related.

EDIT: It is also worth mentioning that this used to work fine but stopped working last year after some update to the chromium engine.

**Comment by gibus** [comment] 2023-10-09 12:44
Hi,

This is weird! I haven't chromium right now but will check later… Meanwhile, can you try to get the js exception, with DevelMode=1 on your RT config. so that we get rid of squished.js and I can see were exactly the exception is raised?

**Comment by gibus** [comment] 2023-10-09 14:53
Finally I manage to try with chromium (Version 112.0.5615.49), but I haven't been able to reproduce your error, everything works fine with RT 5.0.4 and ConditionalCustomFields v1.0.9.

So I need help to reproduce. Which versions (Chromium, RT and ConditioncalCustomFields) do you use? Also if you have a CF "A" and a CF "B", with B conditioned by A, which type and render type (if Select) A and B are? And which Condition (eg. "is" some value)?

Oh and I've forgotten: is the issue on Ticket CFs (or Queue CFs, User CFs, etc.) ?

NB, I'm not sure I can do something if the issue is in Chromium version :-(

**Comment by Wiggen94** [comment] 2023-10-09 20:22
I'm using latest Google Chrome Version 117.0.5938.150. Which version of Chromium it is, I'm not completely sure.

Here is the "unsquished" error message. It only shows up whenever I choose a value in a CF which is supposed to unhide another field. Which it also does whenever I flicker between the values, but error message still shows.

`bootstrap-select.min.js:8 
Uncaught TypeError: Cannot set properties of undefined (setting '_menu')
    at HTMLDivElement.<anonymous> (bootstrap-select.min.js:8:41520)
    at HTMLDivElement.dispatch (jquery-3.6.0.min.js:2:43064)
    at v.handle (jquery-3.6.0.min.js:2:41048)
    at Object.trigger (jquery-3.6.0.min.js:2:71515)
    at HTMLSelectElement.<anonymous> (jquery-3.6.0.min.js:2:72110)
    at Function.each (jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (jquery-3.6.0.min.js:2:1481)
    at S.fn.init.trigger (jquery-3.6.0.min.js:2:72086)
    at HTMLSelectElement.<anonymous> (Display.html?id=370106:5256:35)
    at HTMLSelectElement.dispatch (jquery-3.6.0.min.js:2:43064)`

RT 5.0.4, ConditionalCustomFields v1.0.9. So the parent is a 'Select' and the child is a Select, for the most part.
The condition is if CF A is value x, show CF B. We only have Ticket CFs.
I was thinking, maybe it's the version of jquery that RT ships that causes this? But 3.6.0 is probably not that old yet.

**Comment by gibus** [comment] 2023-10-10 10:35
Thanks. Good news: I've finally managed to reproduce the issue. Actually it was tied to CF B having Dropdown as RenderType. I have to do some more tests but will publish a fix very soon…

**Comment by gibus** [comment] 2023-10-10 14:15
OK, v1.10 should appear soon on MetaCPAN (meanwhile source in github is updated with the fix).

**Comment by Wiggen94** [comment] 2023-10-10 16:49
Great, so I tested it and the actual value in the field shows now and is not "unset" when entering the ticket.
In this case CF A is a dropdown. CF B is a select list and still doesn't show until rechoosing the value in CF A. No errors in console though so there's definitely progress here.

**Comment by gibus** [comment] 2023-10-10 17:17
Ok, I'm not sure to understand correctly:

> Great, so I tested it and the actual value in the field shows now and is not "unset" when entering the ticket.

So, is this fine here?

> In this case CF A is a dropdown. CF B is a select list and still doesn't show until rechoosing the value in CF A. No errors in console though so there's definitely progress here.

Do you mean: CF A can have x, y or z value, CF B is conditioned by CF A is x, and while CF A is actually x, CF B doesn't show up until you select another value (y for eg.) for CF A and then choose x again ?

Or is it another case?

Also are CF A and/or CF B accepting only one value or multiple values? And finally are CF A and/or CF B cascaded CFs, that is based on another CF?

**Comment by Wiggen94** [comment] 2023-10-10 17:20
> Do you mean: CF A can have x, y or z value, CF B is conditioned by CF A is x, and while CF A is actually x, CF B doesn't show up until you select another value (y for eg.) for CF A and then chosse x again ?

Correct. When CF A has value x like it is supposed to when opening a ticket CF B is still hidden until rechoosing value x.
CF A accepts one value and is a dropdown, CF B accepts multiple values. There are no cascading.

And after some further testing I see this is only an issue when CF A is a dropdown. When being a list accepting only one value e.g. it works as expected.

**Comment by gibus** [comment] 2023-10-10 17:22
Ok thanks this is clear, I will try to reproduce it and fix it tomorrow (Paris time)…

**Comment by gibus** [comment] 2023-10-10 17:26
Oh and I realize something:

> when opening a ticket

Here do you mean displaying the ticket? I've only tested today editing the ticket, so I guess there is still something wrong in the Mason component displaying it…

**Comment by Wiggen94** [comment] 2023-10-10 17:27
> Oh and I realize something:
> 
> > when opening a ticket
> 
> Here do you mean displaying the ticket?

Sorry, bad grammar. I mean when initially entering a ticket to edit it.

**Comment by gibus** [comment] 2023-10-10 17:53
> Sorry, bad grammar. I mean when initially entering a ticket to edit it.

Ok meanwhile I was checking the code for display and didn't seen anything that could cause the issue. So it's definitely on editing and I think I have all informations to reproduce it tomorrow…

**Comment by gibus** [comment] 2023-10-11 13:55
Hello @Wiggen94

I've been able to reproduce according to your clear instructions. Solving the issue was tricky but I've finally made it \o/

In details:

The issue was due to the use of bootstrap dropdowns which apply to Select Dropdown CFs, hiding actual select HTML form elements to replace them with some bootstrap magic. But when ConditionalCustomFields tries to check whether a condition on a Dropdown CF is met, it is considered not met if the select HTML form element is not visible (this is to take care of cascaded CFs). The solution was to re-trigger the check when bootstrap dropdown has finished its job (then the HTML form element is visible if it should be displayed).

This works when editing a ticket on Modify.html page, but there was another issue when editing the ticket online (on Display.html page). Here we have to re-trigger the check when the inline form is made visible (by a click on the pen icon).

Also CF grouping (with %CustomFieldGroupings config variable) has to be taken in to account, because in case of inline editing CF A could be in one group and CF B in another group, if only the inline form for grouping of CF B is opened and not the inline form for grouping of CF A, the check has also to done.

I've published v1.11 on MetaCPAN…

**Comment by Wiggen94** [comment] 2023-10-11 17:58
Okay, great it seems to be almost perfect now. However, it seems to only apply for inline editing? If you look on the Modify.html no CF's at all are being hidden. Same for when you are creating a ticket.

I guess whatever you did to fix it for inline-editing broke non-inline in the process somehow?

**Comment by gibus** [comment] 2023-10-11 20:09
Oops I see what is wrong, there is some javascript errors in the console. The issue is to wait for inline form to be visible, even if there is no inline form (because we are on Modify.html). Will fix it tomorrow…

Meanwhile if you wanna try, the patch will just be something like this:

```
diff --git a/html/Elements/EditConditionalCustomFields b/html/Elements/EditConditionalCustomFields
index c17df93..174a78f 100644
--- a/html/Elements/EditConditionalCustomFields
+++ b/html/Elements/EditConditionalCustomFields
@@ -28,11 +28,13 @@ jQuery(function() {
     waitForElm('.dropdown.CF-<% $condition_cf->id %>-Edit').then((elm) => {
         jQuery(condition_selector).trigger('change');
     });
-    respondToVisibility(jQuery('<% $condition_inlineform %>').get(0), visible => {
-        if(visible) {
-            jQuery(condition_selector).trigger('change');
-        }
-    });
+    if (jQuery('<% $condition_inlineform %>').length) {
+        respondToVisibility(jQuery('<% $condition_inlineform %>').get(0), visible => {
+            if(visible) {
+                jQuery(condition_selector).trigger('change');
+            }
+        });
+    }
 %           }
     jQuery(condition_selector).change(function() {
         var cf_id = '<% $cf_id |h,n%>';
```

I have not tested it though, need to be at my office, but I'm confident this will solve the issue…

**Comment by gibus** [comment] 2023-10-12 11:37
This was it, I've integrated this patch on v1.12, with also some other fixes related to cascaded CFs. I hope everything is good now…

**Comment by Wiggen94** [comment] 2023-10-12 14:09
Sounds good! I will test it this weekend!

**Comment by gibus** [comment] 2023-10-26 15:35
I guess I can close this issue now

**Closed as completed by gibus** 2023-10-26 15:35 UTC
